# Nixpacks configuration
# We install runtime libraries for canvas just in case they aren't fully covered by the Puppeteer provider.
[phases.setup]
aptPkgs = [
    "libcairo2",
    "libpango-1.0-0",
    "libpangocairo-1.0-0",
    "libjpeg62-turbo",
    "libgif7",
    "librsvg2-2",
    "libpixman-1-0"
]
